#ifndef PRIVATE_HOLLYWOOD_FLIPPER_AI_REGS_H
#define PRIVATE_HOLLYWOOD_FLIPPER_AI_REGS_H

#define AI_REGISTER_ADDR 0xCD006C00

#define AI_CONTROL 0x0
#define AI_CONTROL_PSTAT (1 << 0)
#define AI_CONTROL_AFR (1 << 1)
#define AI_CONTROL_AIINTMSK (1 << 2)
#define AI_CONTROL_AIINT (1 << 3)
#define AI_CONTROL_AIINTVLD (1 << 4)
#define AI_CONTROL_SCRESET (1 << 5)
#define AI_CONTROL_SAMPLERATE (1 << 6)

#define AI_VOLUME 0x1
#define AI_AISCNT 0x2
#define AI_AIIT 0x3

#endif  // PRIVATE_HOLLYWOOD_FLIPPER_AI_REGS_H
