#ifndef PRIVATE_HOLLYWOOD_DI_REGISTERS_H
#define PRIVATE_HOLLYWOOD_DI_REGISTERS_H

#define DI_REGISTER_ADDR 0xCD006000

#define DI_STATUS 0x0
#define DI_COVER 0x1

#define DI_CMD_BUFFER_0 0x2
#define DI_CMD_BUFFER_1 0x3
#define DI_CMD_BUFFER_2 0x4

#define DI_DMA_MEM_ADDRESS 0x5
#define DI_DMA_TRANSFER_LENGTH 0x6

#define DI_CONTROL 0x7

#define DI_IMMEDIATE_DATA_BUF 0x8
#define DI_CONFIG 0x9

#endif  // PRIVATE_HOLLYWOOD_DI_REGISTERS_H
