#ifndef PRIVATE_HOLLYWOOD_DSP_REGISTERS_H
#define PRIVATE_HOLLYWOOD_DSP_REGISTERS_H

#define DSP_REGISTER_ADDR 0xCC005000

#define DSP_MAILBOX 0x0
#define DSP_MAILBOX_SET 15
#define DSP_MAILBOX_H 0x0
#define DSP_MAILBOX_L 0x1

#define DSP_CPUMAILBOX 0x2
#define DSP_CPUMAILBOX_SET 15
#define DSP_CPUMAILBOX_H 0x2
#define DSP_CPUMAILBOX_L 0x3

#define DSP_CONTROL_STATUS 0x5
#define DSP_CONTROL_STATUS_RESET (1 << 11) /* Apparently this also could be "BOOTMODE" */
#define DSP_CONTROL_STATUS_DMASTAT (1 << 10)
#define DSP_CONTROL_STATUS_ARDMASTAT (1 << 9)
#define DSP_CONTROL_STATUS_DMAINTMSK (1 << 8)
#define DSP_CONTROL_STATUS_DSPINT (1 << 7)
#define DSP_CONTROL_STATUS_ARINTMSK (1 << 6)
#define DSP_CONTROL_STATUS_ARINT (1 << 5)
#define DSP_CONTROL_STATUS_AIDINTMSK (1 << 4)
#define DSP_CONTROL_STATUS_AIDINT (1 << 3)
#define DSP_CONTROL_STATUS_HALT (1 << 2)
#define DSP_CONTROL_STATUS_PIINT (1 << 1)
#define DSP_CONTROL_STATUS_RES (1 << 0)

#define DSP_AR_SIZE 0x9
#define DSP_AR_MODE 0xB
#define DSP_AR_REFRESH 0xC
#define DSP_AR_DMA_MMADDR 0x10
#define DSP_AR_DMA_MMADDR_H 0x10
#define DSP_AR_DMA_MMADDR_L 0x11
#define DSP_AR_DMA_ARADDR 0x12
#define DSP_AR_DMA_ARADDR_H 0x12
#define DSP_AR_DMA_ARADDR_L 0x13
#define DSP_AR_DMA_SIZE 0x14
#define DSP_AR_DMA_SIZE_H 0x14
#define DSP_AR_DMA_SIZE_L 0x15

#define DSP_DMA_START_ADDR_H 0x18
#define DSP_DMA_START_ADDR_L 0x19

#define DSP_DMA_CONTROL_LENGTH 0x1B
#define DSP_DMA_CONTROL_LENGTH_CTRL (1 << 15)

#define DSP_DMA_BYTES_LEFT 0x1D

#endif  // PRIVATE_HOLLYWOOD_DSP_REGISTERS_H
