#ifndef PRIVATE_HOLLYWOOD_MEM_REGISTERS_H
#define PRIVATE_HOLLYWOOD_MEM_REGISTERS_H

#define MEM_REGISTER_ADDR 0xCC004000

#define MEM_MARR_START 0x0
#define MEM_MARR_END 0x1

#define MEM_MARR_REAL_SIZE 0x8
#define MEM_MARR_SIZE 0x2

#define MEM_MARR0_START 0x0
#define MEM_MARR0_END 0x1

#define MEM_MARR1_START 0x2
#define MEM_MARR1_END 0x3

#define MEM_MARR2_START 0x4
#define MEM_MARR2_END 0x5

#define MEM_MARR3_START 0x6
#define MEM_MARR3_END 0x7

#define MEM_MARR_CONTROL 0x8

#define MEM_CP_BW_DIAL 0x9
#define MEM_TC_BW_DIAL 0xA
#define MEM_PE_BW_DIAL 0xB
#define MEM_CPUR_BW_DIAL 0xC
#define MEM_CPUW_BW_DIAL 0xD

#define MEM_INT_ENBL 0xE
#define MEM_INT_STAT 0xF
#define MEM_INT_CLR 0x10
#define MEM_INT_ADDR 0x11
#define MEM_INT_ADDRL 0x11
#define MEM_INT_ADDRH 0x12

#define MEM_REFRESH 0x13

#define MEM_CONFIG 0x14

#define MEM_LATENCY 0x15

#define MEM_RDTORD 0x17

#define MEM_WRTORD 0x18

#define MEM_CP_REQCOUNT 0x19
#define MEM_CP_REQCOUNTH 0x19
#define MEM_CP_REQCOUNTL 0x1A

#define MEM_TC_REQCOUNT 0x1B
#define MEM_TC_REQCOUNTH 0x1B
#define MEM_TC_REQCOUNTL 0x1C

#define MEM_CPUR_REQCOUNT 0x1D
#define MEM_CPUR_REQCOUNTH 0x1D
#define MEM_CPUR_REQCOUNTL 0x1E

#define MEM_CPUW_REQCOUNT 0x1F
#define MEM_CPUW_REQCOUNTH 0x1F
#define MEM_CPUW_REQCOUNTL 0x20

#define MEM_DSP_REQCOUNT 0x21
#define MEM_DSP_REQCOUNTH 0x21
#define MEM_DSP_REQCOUNTL 0x22

#define MEM_IO_REQCOUNT 0x23
#define MEM_IO_REQCOUNTH 0x23
#define MEM_IO_REQCOUNTL 0x24

#define MEM_VI_REQCOUNT 0x25
#define MEM_VI_REQCOUNTH 0x25
#define MEM_VI_REQCOUNTL 0x26

#define MEM_PE_REQCOUNT 0x27
#define MEM_PE_REQCOUNTH 0x27
#define MEM_PE_REQCOUNTL 0x28

#define MEM_RF_REQCOUNT 0x29
#define MEM_RF_REQCOUNTH 0x29
#define MEM_RF_REQCOUNTL 0x2A

#define MEM_FI_REQCOUNT 0x2B
#define MEM_FI_REQCOUNTH 0x2B
#define MEM_FI_REQCOUNTL 0x2C

#define MEM_DRV_STRENGTH 0x2D

#define MEM_REFRSH_THHD 0x2E

#define MEM_CPUAHMR_REQCOUNT 0x30
#define MEM_CPUAHMR_REQCOUNTH 0x30
#define MEM_CPUAHMR_REQCOUNTL 0x31

#define MEM_CPUAHMW_REQCOUNT 0x32
#define MEM_CPUAHMW_REQCOUNTH 0x32
#define MEM_CPUAHMW_REQCOUNTL 0x33

#define MEM_DMAAHMR_REQCOUNT 0x34
#define MEM_DMAAHMR_REQCOUNTH 0x34
#define MEM_DMAAHMR_REQCOUNTL 0x35

#define MEM_DMAAHMW_REQCOUNT 0x36
#define MEM_DMAAHMW_REQCOUNTH 0x36
#define MEM_DMAAHMW_REQCOUNTL 0x37

#define MEM_ACC_REQCOUNT 0x38
#define MEM_ACC_REQCOUNTH 0x38
#define MEM_ACC_REQCOUNTL 0x39

#define MEM_DDRREG_ADDR 0x3A

#define MEM_DDRREG_DATA 0x3B

#define MEM_DRV_PSTRENGTH 0x3C

#define MEM_INT_MEM_0 (1 << 0)
#define MEM_INT_MEM_1 (1 << 1)
#define MEM_INT_MEM_2 (1 << 2)
#define MEM_INT_MEM_3 (1 << 3)
#define MEM_INT_MEM_ADDRESS (1 << 4)

#endif  // PRIVATE_HOLLYWOOD_MEM_REGISTERS_H
