#ifndef PRIVATE_HOLLYWOOD_FLIPPER_PI_REGS_H
#define PRIVATE_HOLLYWOOD_FLIPPER_PI_REGS_H

#define PI_REGISTER_ADDR 0xCC003000

#define PI_INTERRUPT_CAUSE 0x0
#define PI_INTERRUPT_ERROR (1 << 0)
#define PI_INTERRUPT_RSW (1 << 1)
#define PI_INTERRUPT_DI (1 << 2)
#define PI_INTERRUPT_SI (1 << 3)
#define PI_INTERRUPT_EXI (1 << 4)
#define PI_INTERRUPT_AI (1 << 5)
#define PI_INTERRUPT_DSP (1 << 6)
#define PI_INTERRUPT_MEM (1 << 7)
#define PI_INTERRUPT_VI (1 << 8)
#define PI_INTERRUPT_PE_TOKEN (1 << 9)
#define PI_INTERRUPT_PE_FINISH (1 << 10)
#define PI_INTERRUPT_CP (1 << 11)
#define PI_INTERRUPT_DEBUG (1 << 12)
#define PI_INTERRUPT_HSP (1 << 13)
#define PI_INTERRUPT_ACR (1 << 14) /* HOLLYWOOD EXCLUSIVE */
#define PI_INTERRUPT_RSW_STATE (1 << 16)

#define PI_INTERRUPT_MASK 0x1

#define PI_RESET_REQUEST 0x9
#define PI_UNIT_INFO 0xB
#define PI_UNIT_INFO_TYPE 28
#define PI_UNIT_INFO_TYPE_EB 31

#endif  // PRIVATE_HOLLYWOOD_FLIPPER_PI_REGS_H
