#ifndef PRIVATE_HOLLYWOOD_FLIPPER_SI_REGS_H
#define PRIVATE_HOLLYWOOD_FLIPPER_SI_REGS_H

#define SI_REGISTER_ADDR 0xCC006400

#define SI_OUT_BUFFER 0x0
#define SI_BUTTON_BUFFER 0x1
#define SI_BUTTON_2_BUFFER 0x2

#define SI_BUFFER_REAL_SIZE 0xC
#define SI_BUFFER_SIZE 0x3

#define SI_0_OUT_BUFFER 0x0
#define SI_0_BUTTON_BUFFER 0x1
#define SI_0_BUTTON_2_BUFFER 0x2

#define SI_1_OUT_BUFFER 0x3
#define SI_1_BUTTON_BUFFER 0x4
#define SI_1_BUTTON_2_BUFFER 0x5

#define SI_2_OUT_BUFFER 0x6
#define SI_2_BUTTON_BUFFER 0x7
#define SI_2_BUTTON_2_BUFFER 0x8

#define SI_3_OUT_BUFFER 0x9
#define SI_3_BUTTON_BUFFER 0xA
#define SI_3_BUTTON_2_BUFFER 0xB

#define SI_JOY_POLL 0xC

#define SI_CONTROL_STATUS 0xD
#define SI_CONTROL_STATUS_TCINT (1 << 31)
#define SI_CONTROL_STATUS_TCINTMSK (1 << 30)
#define SI_CONTROL_STATUS_COMERR (1 << 29)
#define SI_CONTROL_STATUS_RDSTINT (1 << 28)
#define SI_CONTROL_STATUS_RDSTINTMSK (1 << 27)

#define SI_CONTROL_STATUS_TSTART (1 << 0)

#define SI_STATUS 0xE

#define SI_EXI_CLOCK 0xF

#define SI_IO_BUFFER 0x20

#endif  // PRIVATE_HOLLYWOOD_FLIPPER_SI_REGS_H
