#ifndef PRIVATE_HOLLYWOOD_VI_REGISTERS_H
#define PRIVATE_HOLLYWOOD_VI_REGISTERS_H

#define VI_REGISTER_ADDR 0xCC002000

#define VI_VERTICAL_TIME 0x0

#define VI_DISPLAY_CONFIG 0x1

#define VI_HORIZONTAL_TIME0 0x2
#define VI_HORIZONTAL_TIME1 0x4

#define VI_VERTICAL_TIME_ODD_FIELD 0x6
#define VI_VERTICAL_TIME_EVEN_FIELD 0x8

#define VI_BURST_BLANK_ODD_FIELD 0xA
#define VI_BURST_BLANK_EVEN_FIELD 0xC

#define VI_TOP_FIELD_BASE_L 0xE
#define VI_TOP_FIELD_BASE_R 0x10

#define VI_BOTTOM_FIELD_BASE_L 0x12
#define VI_BOTTOM_FIELD_BASE_R 0x14

#define VI_VERTICAL_POSITION 0x16
#define VI_HORIZONTAL_POSITION 0x17

#define VI_DISPLAY_INTERRUPT_0 0x18
#define VI_DISPLAY_INTERRUPT_1 0x1A
#define VI_DISPLAY_INTERRUPT_2 0x1C
#define VI_DISPLAY_INTERRUPT_3 0x1E

#define VI_DISPLAY_L_INTERRUPT_0 0x20
#define VI_DISPLAY_L_INTERRUPT_1 0x22

#define VI_SCALE_WIDTH 0x24
#define VI_HORIZONTAL_SCALE 0x25

#define VI_FILTER_TABLE_0 0x26
#define VI_FILTER_TABLE_1 0x28
#define VI_FILTER_TABLE_2 0x2A
#define VI_FILTER_TABLE_3 0x2C
#define VI_FILTER_TABLE_4 0x2E
#define VI_FILTER_TABLE_5 0x30
#define VI_FILTER_TABLE_6 0x32

#define VI_UNKNOWN_AA_STUFF 0x34

#define VI_CLOCK_SELECT 0x36
#define VI_CLOCK_SELECT_54MHZ (1 << 0)
#define VI_DTV_STATUS 0x37

#define VI_UNKNOWN_70 0x38

#define VI_HBE_BORDER 0x39
#define VI_HBS_BORDER 0x3A

#endif  // PRIVATE_HOLLYWOOD_VI_REGISTERS_H
