#ifndef REVOLUTION_SC_H
#define REVOLUTION_SC_H

#include <revolution/types.h>

#define SC_LANG_JAPANESE 0
#define SC_LANG_ENGLISH 1
#define SC_LANG_GERMAN 2
#define SC_LANG_FRENCH 3
#define SC_LANG_SPANISH 4
#define SC_LANG_ITALIAN 5
#define SC_LANG_DUTCH 6
#define SC_LANG_SIMP_CHINESE 7
#define SC_LANG_TRAD_CHINESE 8
#define SC_LANG_KOREAN 9
#define SC_LANG_MAX 10

u8 SCGetLanguage();
BOOL SCSetLanguage(u8 language);

#define SC_PRODUCT_GAME_REGION_UNKNOWN -1
#define SC_PRODUCT_GAME_REGION_JP 0
#define SC_PRODUCT_GAME_REGION_US 1
#define SC_PRODUCT_GAME_REGION_EU 2
#define SC_PRODUCT_GAME_REGION_ALL 3 /* ? */
#define SC_PRODUCT_GAME_REGION_KR 4
#define SC_PRODUCT_GAME_REGION_CN 5

s8 SCGetProductGameRegion();

#endif  // REVOLUTION_SC_H
