#!/usr/bin/env python3

###
# Split library archive to objects
#
# Usage:
#   python3 tools/split_ar.py --dtk-version 1.0.0 --dtk dtk --output output config.json
#
###


import argparse
import io
import sys
import os
import platform
import shutil
import stat
import csv
import subprocess
import json

from pathlib import Path
from ar.archive import Archive


def get_disc_file(path_find):
    for filename in path_find.iterdir():
        if filename.is_file() and filename.suffix in [
            '.iso', '.wbfs', '.rvz', '.wia',
            '.cios', '.nfs', '.gcz', '.tgc'
        ]:
            return filename


# Simple function :P
def write_file(output_path: Path, data) -> None:
    with open(output_path, 'wb') as file:
        file.write(data)

# Module configuration
class ArchiveConfig:
    name: str
    obj_paths: str
    disc_path: str
    arch_path: str

class DTKConfigMain:
    def __init__(self, name, version):
        self.name = name
        self.version = version
        self.units = []
        
        # not important
        self.module_id = 0
        self.ldscript = ""
        self.entry = ""
        self.modules = []
        self.links = []

    def add_unit(self, object: str, name: str):
        self.units.append({"object": object, "name": name, "autogenerated": False})


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, help="output directory path", required=True)
    parser.add_argument("--dtk-version", type=str, help="dtk version", required=True)
    parser.add_argument("--dtk", type=str, help="dtk path", required=True)
    parser.add_argument("config", type=Path, help="input config.json file path")
    args = parser.parse_args()


    # print("Reading configuration...")


    # Read configuration file
    with open(args.config, "r", encoding="utf-8") as archive_file_handle:
        archive_configs: list[ArchiveConfig] = json.load(archive_file_handle)

    dtk_configs: list[DTKConfigMain] = []
    for archive_config in archive_configs:
        # Read settings from configuration
        config_archive_name = archive_config.get("name")
        config_disc_path = Path(archive_config.get("disc_path"))
        config_paths_file = Path(archive_config.get("obj_paths"))
        config_input_file = Path(archive_config.get("arch_path"))


        # Use archive file name if no name is specified.
        if not config_archive_name:
            config_archive_name = config_input_file.stem


        # If we are extracting from a disc.
        if config_disc_path:
            extract_path = archive_config.get("arch_path")

            config_input_file = config_disc_path / extract_path
            config_input_file.parent.mkdir(parents=True, exist_ok=True)
            
            if not config_input_file.is_file() or not config_input_file.exists():
                disc_input = get_disc_file(config_disc_path)

                if not disc_input:
                    print("ERROR: Disc not found!")
                    print()
                    print("Please copy a disc image into \"" + str(config_disc_path) + "\"")
                    print("If you are not extracting an archive from a disc, remove \"disc_path\" from config.json")
                    print()
                    sys.exit(1)

                disc_input = str(disc_input) # sure :)

                compiled_full_path = disc_input + ":files/" + extract_path
                subprocess.check_output([args.dtk, 'vfs', 'cp', compiled_full_path, str(config_input_file)])


        # running_system = platform.uname().system.lower()
        # running_windows = running_system == "windows"
        
        
        def get_abs_path(my_path):
            return Path(os.path.abspath(os.path.join(args.output, my_path)))
        
        
        def get_path(my_path):
            return Path(os.path.join(args.output, my_path))


        # Get output paths
        obj_path = get_abs_path("obj")
        asm_path = get_abs_path("asm")
        dtk_config_path = get_abs_path("config.json")


        # print("Splitting...")


        # Prepare DTK config
        dtk_config = DTKConfigMain(config_archive_name, args.dtk_version)
        # Open archive file
        with open(config_input_file, 'rb') as archive_file_handle:
            ar_input_file = Archive(archive_file_handle)
            # Open paths file
            with open(config_paths_file, 'r') as paths_file_handle:
                # Now let's go through the entries
                reader = csv.reader(paths_file_handle, delimiter='\t')
                for file_entry in reader:

                    # Get path entry info

                    ar_file_full_name = file_entry[1]
                    ar_file_name = os.path.basename(ar_file_full_name)

                    ar_file_obj = os.path.splitext(ar_file_full_name)[0] + ".o"
                    ar_file_obj_name = os.path.basename(ar_file_obj)

                    ar_file_asm = os.path.splitext(ar_file_full_name)[0] + ".s"

                    ar_file_output_dtkpath = Path(os.path.join(get_path("obj"), ar_file_obj))
                    ar_file_output_fullpath = Path(os.path.join(obj_path, ar_file_obj))
                    ar_file_disasm_fullpath = Path(os.path.join(asm_path, ar_file_asm))

                    ar_file_duplicate = int(file_entry[0])

                    # For objects that may have the same name and location
                    duplicate = 1
                    for ar_entry in ar_input_file:
                        # If the name and duplicate matches, we got one!
                        if ar_entry.name == ar_file_obj_name and duplicate == ar_file_duplicate:
                            # Extract object
                            ar_file_output_fullpath.parent.mkdir(parents=True, exist_ok=True)
                            write_file(ar_file_output_fullpath, ar_input_file.open(ar_entry, 'rb').read())
                            
                            # Disassemble object
                            ar_file_disasm_fullpath.parent.mkdir(parents=True, exist_ok=True)
                            subprocess.check_output([args.dtk, 'elf', 'disasm', ar_file_output_fullpath, ar_file_disasm_fullpath])

                            # Add to DTK config
                            dtk_config.add_unit(str(ar_file_output_dtkpath), str(ar_file_full_name))

                            # Next object!
                            break

                        # If the name matches but not the duplicate, then we goto the next object, finding the next duplica
                        if ar_entry.name == ar_file_obj_name and not duplicate == ar_file_duplicate:
                            duplicate += 1

                        continue


        # print("Writing DTK config...")

        #json.dump(dtk_config.__dict__, dtk_config_file_handle, indent=2)
        dtk_configs.append(dtk_config)

    cfg = dtk_configs[0]
    if len(dtk_configs) > 1:
        cfg.modules = [c.__dict__ for c in dtk_configs[1:]]

    dtk_config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(dtk_config_path, 'w') as dtk_config_file_handle:
        json.dump(cfg.__dict__, dtk_config_file_handle, indent=2)



    # print("Done!")

# entry
if __name__ == "__main__":
    main()
